import type { Metadata } from "next";
import { Inter } from "next/font/google";
import {  Poppins } from "next/font/google";
import "./globals.css";
import Head from "next/head";
import Footer from '@/app/components/footer'


const inter = Inter({ subsets: ["latin"] });
const poppins = Poppins({ subsets: ["latin"], weight: ["400", "500", "600"] });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <body className={`${poppins.className} ${inter.className}`}>
        {children}
        <Footer />
      </body>
    </html>
  );
}
